server:
  port: 8088
  servlet:
    context-path: /OnlineLearning
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OnlineLearning?characterEncoding=UTF-8&&serverTimezone=GMT
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true 
      max-file-size: -1 
      max-request-size: -1 
file:
  server:
    dir: upload/
    path: /upload/
mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


